/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.jiffy.gradle.cmake.swig.starter;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
